name: Deploy and SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Airline Main Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Deploy Airline Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ip }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: ./test.sh
